create table if not exists public.profiles (
    id uuid primary key references auth.users (id) on delete cascade,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    avatar_url text,
    avatar_path text,
    first_name text,
    middle_name text,
    last_name text,
    given_name text,
    family_name text,
    email text,
    email_address text,
    phone text,
    phone_number text,
    dob date,
    date_of_birth date,
    id_number text,
    nationality text,
    country_of_citizenship text,
    country_of_birth text,
    country_residence text,
    country text,
    country_of_tax_residence text,
    tax_residency text,
    tax_number text,
    tax_id text,
    tax_id_type text,
    street_address text,
    street_address_line1 text,
    street_address_line2 text,
    street_address_line3 text,
    street_address_unit text,
    unit text,
    city text,
    state text,
    postal_code text,
    funding_source text,
    liquidity_needs text,
    investment_experience_with_stocks text,
    investment_experience_with_options text,
    investment_objective text,
    investment_time_horizon text,
    annual_income_min numeric,
    annual_income_max numeric,
    liquid_net_worth_min numeric,
    liquid_net_worth_max numeric,
    total_net_worth_min numeric,
    total_net_worth_max numeric,
    visa_type text,
    visa_expiration_date date,
    date_of_departure_from_usa date,
    permanent_resident boolean default false,
    marital_status text,
    number_of_dependents integer,
    employment_status text,
    occupation text,
    employer text,
    income_bracket text,
    source_of_funds text,
    net_worth_range text,
    experience_level text,
    risk_tolerance text,
    objectives text,
    pep boolean default false,
    fatca_crs boolean default false,
    plan text,
    profile_complete boolean generated always as (
        (coalesce(first_name, '') <> '' and coalesce(last_name, '') <> '')
    ) stored,
    has_uploaded_id_doc boolean default false,
    has_uploaded_address_proof boolean default false,
    twofa_preference text,
    terms_accepted boolean default false,
    popia_consent boolean default false,
    samsub_external_user_id text,
    samsub_applicant_id text,
    samsub_websdk_url text,
    samsub_status text default 'not_started',
    samsub_last_updated timestamptz,
    kyc_status text default 'unverified',
    kyc_applicant_id text,
    kyc_reference text,
    kyc_external_user_id text,
    kyc_started_at timestamptz,
    kyc_verified_at timestamptz
);
